name: JS Actions workflow

on:
  issues:
    types: [labeled]
  push:
    branches: [main] 
    # - main

jobs:
  action-job:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
      - name: "fetch a joke"
        uses: ./.github/actions/joke-action

